export default {
  NOT_FOUND: 'NOT_FOUND',

  FILENAME_MUST_HAVE_A_VALUE: 'FILENAME_MUST_HAVE_A_VALUE',
  FILENAME_MUST_BE_A_STRING: 'FILENAME_MUST_BE_A_STRING',
  MIMETYPE_MUST_BE_A_STRING: 'MIMETYPE_MUST_BE_A_STRING',
  SECTION_MUST_HAVE_A_VALUE: 'SECTION_MUST_HAVE_A_VALUE',
  SECTION_MUST_BE_A_STRING: 'SECTION_MUST_BE_A_STRING',
};
